# Copy .env.example to .env and adjust PORT if needed.
# Copy this file to compose.yaml and run: docker compose up -d
services:
  surge:
    image: ghcr.io/cheminfo/surge:latest
    restart: unless-stopped
    env_file: .env
    ports:
      - '127.0.0.1:${PORT:-31228}:${PORT:-31228}'
    init: true # allows to kill the process
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    cap_drop:
      - ALL
    logging:
      driver: 'json-file'
      options:
        max-size: '200m'
        max-file: '3'
    ulimits:
      core: 0 # We don't want core dump, we never analyse them anyway
      nofile: 256 # Max number of files that can be open
      nproc: 32 # Mas number of processes
    mem_limit: '256m' # max memory
    cpus: 2 # max 2 CPU cores
