services:
  surge:
    image: ghcr.io/cheminfo/surge:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:31228:31228
    ulimits:
      core: 0 # We don't want core dump, we never analyse them anyway
      nofile: 65536 # Max number of files that can be open
      nproc: 10240 # Mas number of processes
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=100m
    mem_limit: 2G # max memory
    cpus: 2 # max 2 CPU cores
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
        max-file: 3
